### ISSUE TITLE
Ports?

### ISSUE THREAD

**Issue by 9dc** [markdegrootnl/unifi-protect-arm64#10]
not an Issue but a question.

Do you know which ports protect is using?

i want to use port 80 on my machine.

thanks.

**Comment by trenb** [comment]
If you run with the recommended docker command, it will use host mode networking, which means all the ports that unifi protect sets up will be accessible via the IP of the docker host.

**Comment by markdegrootnl** [comment]
Looking at my own installation I see the following open ports:

UniFi Core:
* 443
* 80

UniFi Protect:
* 7442
* 7443
* 7444
* 7600
* 7877
* 7888
* 7550
* 7451
* 7441
* 7445
* 7446
* 7447

Like @trenb said, the container needs to run with host mode networking, so It can open all ports needed.
