### ISSUE TITLE
changing required disk size

### ISSUE THREAD

**Issue by Sputnick85** [markdegrootnl/unifi-protect-arm64#12]
You can change the size of the required disk size by changeing the file _**/usr/share/unifi-protect/app/config/config.json**_. This will help to start protect on small disks.

If you change the parameter **mbToKeepFree** to something like this:
```
"mbToKeepFree": 1024,
```
You can easily use this on a raspberry with 32GB SD Card

By default the value is around 66GB

**Comment by markdegrootnl** [comment]
Great find! Feel free to submit a PR to add it to the readme.

**Comment by Sputnick85** [comment]
#13 

done,  closed
