### ISSUE TITLE
Unstable container

### ISSUE THREAD

**Issue by Thijxx** [markdegrootnl/unifi-protect-arm64#3]
The container generates 60% CPU load with 0 camera's connected. 24/7.
The container is unstoppable, there is absolutely no way to stop it. Not with docker, not with kill -9, just no way.
Trying to brute force stop the container halts the system, then it needs a power cycle.

I tried it with 3 Pi 4's with 8GB RAM running from USB 3.0 NVME disks.

**Comment by markdegrootnl** [comment]
"Unstoppable", it sounds like a good thing...

I personally don't experience this behaviour. Which container version are you running? Are there any logs that might provide more insight?

**Comment by 9dc** [comment]
same happend for me.
website unreachable, container not stoppable, had to reboot the pi.

PI 4 8 GB RAM, latest container version, ubuntu

**Comment by 9dc** [comment]
with the current version of this container, i didnt had the problem again. i think its fixed.

**Comment by markdegrootnl** [comment]
@Thijxx How's your experience running the latest version?

**Comment by Thijxx** [comment]
@markdegrootnl I did not continue with the camera's but can try again as a nice start of the new year :D

**Comment by Thijxx** [comment]
The extreme CPU usage seems to be fixed. That is nice! Running it is still hard, using docker-compose it finally worked but the the setup failed with the completely useless message: "An unexpected error occured during setup." But that's just Ubiquiti quality software :D
