### ISSUE TITLE
Unable to do inline update to 2.2.7

### ISSUE THREAD

**Issue by Sub-lime-time** [markdegrootnl/unifi-protect-arm64#4]
Just wondering if this is still being maintained? The update feature doesn't work to get to the latest shipping version of Uniifi OS (2.2.7) which also enables Protect 1.19.

**Comment by markdegrootnl** [comment]
Hi Greg, This repo is still maintained. Since it's a docker container, there really is no such thing as inline updating. Every time you restart the container, all files not in a persistent volume are reset to the image version.

**Comment by Sub-lime-time** [comment]
Thanks @markdegrootnl for the clarification (head slap). Of course, makes total sense.
