### ISSUE TITLE
UNVR Setup Error: An unexpected error occured during setup.

### ISSUE THREAD

**Issue by MastaP** [markdegrootnl/unifi-protect-arm64#6]
Hi,

Started the container using `docker run` command. In web UI, after pressing Finish in the setup process I get the error. 
First, I tried restarting the container and setting folder permissions to 777, did not help.
Inside the container `more /var/log/postgresql/postgresql-9.6-main.log` had:
```
2021-10-10 14:52:20.424 UTC [330] postgres@ulp-go FATAL:  database "ulp-go" does not exist
2021-10-10 14:52:21.473 UTC [353] postgres@ulp-go-syslog FATAL:  database "ulp-go-syslog" does not exist
2021-10-10 15:33:34.099 UTC [82] FATAL:  data directory "/data/postgresql/9.6/main/data" has group or world access
2021-10-10 15:33:34.099 UTC [82] DETAIL:  Permissions should be u=rwx (0700).
```
So I've set the permissions to 700, the error above went away.

Then, looking into `/srv/unifi-protect/logs/errors.log`:
```
2021-10-10T15:48:58.410Z - error: Cannot connect to database. connect ENOENT /var/run/postgresql/.s.PGSQL.5433
2021-10-10T15:48:58.420Z - error:  Error: connect ENOENT /var/run/postgresql/.s.PGSQL.5433
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
2021-10-10T15:49:33.274Z - error: DEVICE NOT REGISTERED unregistered-hardware
```

Any ideas?

**Comment by ozett** [comment]
similar error after starting docker on my jetson-nano
enough space, but similar errors.
any hint or solution how to overcame this?

![image](https://user-images.githubusercontent.com/5937811/147213663-e1cf92cf-980d-41dc-a8e8-eaeb56a59339.png)

**Comment by markdegrootnl** [comment]
Which version of the Docker container are you running?

**Comment by MastaP** [comment]
I used 1.15.0

**Comment by ozett** [comment]
Docker version 20.10.7, build 20.10.7-0ubuntu5~18.04.3

edit: image was latest:
```
 docker run --name unifi-protect-arm64      --privileged     --tmpfs /run     --tmpfs /run/lock     --tmpfs /tmp     -v /sys/fs/cgroup:/sys/fs/cgroup:ro     -v /mnt/nfsunifi/srv:/srv     -v /mnt/nfsunifi/data:/data     --network host     markdegroot/unifi-protect-arm64:latest
```


fresh jetson nano-os:
![image](https://user-images.githubusercontent.com/5937811/147229488-681053de-a36f-4257-853b-ccc8c3f2c890.png)

**Comment by ozett** [comment]
must this be fixed?

![image](https://user-images.githubusercontent.com/5937811/147232737-830f806c-7d15-4166-825b-7c6c0c6d4ad8.png)

**Comment by ozett** [comment]
exchanged the jetson-storage (was an nfs-mount for 100 GB free) with a usb-ssd on ext4.
no luck.
also not used the :latest docker-image
no luck.

is this meant to be run without error on the docker-command from the readme.md?
i think so (like others) but now a littel clueless how to get it running..

maybe some mdadm/ub-storage defaults or mappings are missing 
to assemble the /md3 raid from the inital setup?

![image](https://user-images.githubusercontent.com/5937811/147238663-c66d1153-0c88-4c34-9a76-6b84f3c332a5.png)

**Comment by ozett** [comment]
maybe its the firmware 2.2.7 itself? update [to 2.2.12](https://community.ui.com/releases/UniFi-OS-Network-Video-Recorders-2-2-12/419e87b7-0774-4a57-b26c-d1a0f3400aab?page=2) ?

```
root@UNVR:/# cat /usr/lib/version
UNVR4.al324.v2.2.7.2aa2917.210824.1401
root@UNVR:/# cat /proc/md
```

**Comment by markdegrootnl** [comment]
Try pulling the latest version of the docker container (1.20.1):
```docker pull markdegroot/unifi-protect-arm64:latest```
or specify the version of the container in your run command.

**Comment by ozett** [comment]
i cleared existing images and pulled the latest.
to make shure its version 1.20.1 i specified this for the docker-run, but it pulled (anohter?) again..
will report later the result...

```
docker rm $(docker ps -a -q)
docker rmi $(docker images -q)
docker pull markdegroot/unifi-protect-arm64:latest
```
![image](https://user-images.githubusercontent.com/5937811/147248822-be5adeca-706e-4ba8-bdff-554a584c9ddd.png)

**Comment by ozett** [comment]
did not help


any other things to check ?
-- inside the container running the asisstant?
must there be (mapped) raid-disk inside? which?

can i stay with this? raid10 also thows the same error..

![image](https://user-images.githubusercontent.com/5937811/147249282-aae9a9a1-5336-48f4-980d-a1bb19ecb762.png)

**Comment by markdegrootnl** [comment]
You just select the "One Disk" option.

Could you check the logs inside the container in `/data/unifi-core`

**Comment by ozett** [comment]
i went through some of the logs... but did not catch a hint...
the ub-storage service complaints about missing /dev/md3

i assume that the assistant does not assemble the raid .
maybe because of faulty docker-mappings for disk-path into the containter?

or something specific to look for?

WEIRD cleaning of images as i wanted to see if that also happening with image tagged 1.19.0...
will report in a minute...

![image](https://user-images.githubusercontent.com/5937811/147250724-b8ded5bc-4879-4707-8ed0-8878a507c61c.png)

**Comment by ozett** [comment]
ver 1.19.0 also not running on the jetson-nano arm...
some specific differences to the raspberry? naming of the disc?

![image](https://user-images.githubusercontent.com/5937811/147251012-5f1455b8-0e9f-4fff-9633-dbe092db8e7c.png)

**Comment by ozett** [comment]
> You just select the "One Disk" option.
> 
> Could you check the logs inside the container in `/data/unifi-core`

dont know whats relevant, but  in ```system.log``` (need to fix this?)
```

2021-12-23T14:02:09.787Z - error: error retrieving setup device id Error: EACCES: permission denied, mkdir '/persistent/unifi-core'
2021-12-23T14:02:21.187Z - error: error retrieving setup device id Error: EACCES: permission denied, mkdir '/persistent/unifi-core'
2021-12-23T14:02:31.333Z - error: error retrieving setup device id Error: EACCES: permission denied, mkdir '/persistent/unifi-core'
2021-12-23T14:02:31.551Z - error: error retrieving setup device id Error: EACCES: permission denied, mkdir '/persistent/unifi-core'
2021-12-23T14:02:33.768Z - error: error retrieving setup device id Error: EACCES: permission denied, mkdir '/persistent/unifi-core
```

**Comment by ozett** [comment]
The assistand never finishes, and i see port-errors in the log,
but thats the status ```netstat -tulpn``` without the assistant getting finish:

![image](https://user-images.githubusercontent.com/5937811/147252880-a92d4d46-6119-4757-a60a-2ebc707427c3.png)

**Comment by ozett** [comment]
any idea what to check for the building of the raid from assistant??
found some info for that, but no clue how to assemble it by hand into the docker containter...
https://community.ui.com/questions/Trouble-adding-NVR-to-full-Unifi-network-UniFi-Protect-NVR-Setup-Error/51d9f514-4da3-42cd-ba8a-835699eb2fc4#answer/a4ca0c1f-2fb7-4327-98b7-4356f839fce5

**Comment by ozett** [comment]
this also did not help:
![image](https://user-images.githubusercontent.com/5937811/147259547-c26ee5d1-980c-4f6b-b905-9a036952e8d2.png)

i made some empty files, mounted them as loop-devices and mapped them into the container as disks
```
dd if=/dev/zero of=raid-2 bs=1M count=500
dd if=/dev/zero of=raid-3 bs=1M count=500

losetup /dev/loop2 raid-2
losetup /dev/loop3 raid-3
```

```
docker run --name unifi-protect-arm64  \
    --privileged \
    --tmpfs /run \
    --tmpfs /run/lock \
    --tmpfs /tmp \
     --shm-size=64m \
    -v /sys/fs/cgroup:/sys/fs/cgroup:ro \
    -v /media/olaf/ff3594e6-3f3f-4133-98c3-1ad49278c650/srv:/srv \
    -v /media/olaf/ff3594e6-3f3f-4133-98c3-1ad49278c650/data:/data \
    -v /dev/loop2:/dev/sda2 \
    -v /dev/loop3:/dev/sda3 \
    --network host \
    -m 2048m \
    markdegroot/unifi-protect-arm64:latest
```

still error at the end of the assistant...
any clues?

**Comment by ozett** [comment]
fail, fail, fail...

could that work inside docker for the NVR?
https://serverfault.com/questions/1001912/is-it-possible-to-use-software-raid-inside-a-docker-container

![image](https://user-images.githubusercontent.com/5937811/147260278-15a9d56a-35c4-4f3a-b4fa-cec4e8254eaf.png)

**Comment by ozett** [comment]
are there files missing?
![image](https://user-images.githubusercontent.com/5937811/147264896-44696db3-cd4a-461b-bfb6-8d29d1952aec.png)

**Comment by ozett** [comment]
fail with docker image v1.19.0 & 1.18.0
succes with docker v 1.17.3

![image](https://user-images.githubusercontent.com/5937811/147284409-e1e6aadd-c3d7-44ee-8ed7-82981928bc26.png)

**Comment by ozett** [comment]
it runs unstable, 
but all i wanted was to activat my g3 instant.
that somehow was succes with the android app on your docker-image v1.17.3....
thanks a lot.
(the whole thing seems to be unusable for production. somehow only for lab-experiments..)

![image](https://user-images.githubusercontent.com/5937811/147285602-2dcd8b72-b9d1-49d9-9d38-30288cc8cac9.png)

**Comment by ozett** [comment]
the app adopted the cam, made an error.
cannot see how to switch the cam now to stand-alone mode (like the g3) or if its possible at all..
![image](https://user-images.githubusercontent.com/5937811/147287750-b7c9d3db-55ab-48d7-b9f3-fdeb57c83753.png)

**Comment by Thijxx** [comment]
Having the same problem here..

Lots of these in **errors.log** in **unifi-core**: `stderr: /bin/sh: 1: ustorage: not found`
Also: `mdadm: cannot open /dev/md3: No such file or directory`

**trace.log**
```
2022-01-03T09:20:00.890Z - warn: Error during metric send
2022-01-03T09:20:00.891Z - warn:  FetchError: request to https://trace.svc.ui.com/traces failed, reason: unable to get local issuer certificate
    at ClientRequest.<anonymous> (/usr/share/unifi-core/app/webpack:/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Also loads of "sudo password needed" in the logs.

**Comment by markdegrootnl** [comment]
The errors are fine. That's just due to running on own hardware.
Please update the docker image to the latest version 1.20.3
