### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by 9dc** [markdegrootnl/unifi-protect-arm64#8]
Hi, is it possible to update the UNVR?

![image](https://user-images.githubusercontent.com/11146776/147911435-6de2d200-f61e-4b22-92fd-a97cc53bb3e1.png)

Every time i do it, nothing happens after the Site is refreshing.
Any idea?
thxx

**Comment by markdegrootnl** [comment]
No that's not possible. I'll create an updated Docker image for this release soon.

**Comment by markdegrootnl** [comment]
Docker container has been updated to UniFi OS 2.3.10 / UniFi Protect 1.20.3
