### ISSUE TITLE
Storage space requirements - guide

### ISSUE THREAD

**Issue by ludiaribar** [markdegrootnl/unifi-protect-arm64#9]
This works fine on Odroid-C4 with 16GB SD card and 250Gb USB SSD. Thanks!

However the container needs more than 16GB of storage to run so either the primary storage needs to be bigger, or the arguments:

  -v /storage/srv:/srv \
    -v /storage/data:/data \

 modified to:

  -v /storage/srv:/PATH_TO_BIGGER_STORAGE \
    -v /storage/data:/PATH_TO_BIGGER_STORAGE \

**Comment by markdegrootnl** [comment]
This is mentioned in the readme:

> UniFi Protect needs a lot of storage to record video. Protect will fail to start if there is not at least 100GB disk space available, so make sure to store your Docker volumes on a disk with some space (/storage in the above run command).
